name: Build and Deploy to Azure

on:
  push:
    branches:
      - main

env:
  IMAGE_TAG: latest
  AZURE_STORAGE_ACCOUNT_NAME: ${{ env.AZURE_STORAGE_ACCOUNT_NAME }}
  AZURE_STORAGE_CONTAINER_NAME: ${{ env.AZURE_STORAGE_CONTAINER_NAME }}
  AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t oca-browser:$IMAGE_TAG .
      
      - name: Copy assets from builder
        run: docker create --name oca-browser-container oca-browser:$IMAGE_TAG && docker cp oca-browser-container:/app/dist ./ && docker rm oca-browser-container
      
      - name: Upload to Azure Blob Storage
        uses: Azure/blob-storage-upload@v1
        with:
          connection_string: ${{ env.AZURE_STORAGE_CONNECTION_STRING }}
          container_name: ${{ env.AZURE_STORAGE_CONTAINER_NAME }}
          source: ./dist

